DROP TABLE IF EXISTS NameBasics;

DROP TABLE IF EXISTS TitleAkas;

DROP TABLE IF EXISTS TitleBasics;

DROP TABLE IF EXISTS Crew;

DROP TABLE IF EXISTS Episode;

DROP TABLE IF EXISTS Prinicipals;

DROP TABLE IF EXISTS Ratings;